### ISSUE TITLE
Obtain a DOI for RK-Opt via Zenodo

### ISSUE THREAD

**Issue by ranocha** [ketch/RK-opt#43]
To cite RK-Opt, it might be nice to have a DOI from https://zenodo.org/. If you want, I can set up a `.zenodo.json` file.

**Comment by ketch** [comment]
In the past I have been given the advice that DOIs are intended to be attached to documents and not to code.  I know that we use them for reproducibility repositories, but those are closely related to a specific 0document.  Has that advice changed?

It's also not clear to me how having a DOI would work with code as the code changes.

**Comment by ranocha** [comment]
I'm not sure whether there is a general consensus on whether or not software should be cited using a DOI.

Zenodo provides 

- one DOI for the code as a whole and
- additional DOIs for every version (GitHub release) of the code.

Hence, people can either cite the code in an abstract way or using the DOI for the specific version they have applied.

**Comment by ketch** [comment]
Yes, that's how I understood your suggestion, and I'm open to the idea.  I've also considered publishing a short paper somewhere with all the contributors as authors.

**Comment by ranocha** [comment]
That's of course also a possibility. As far as I know, there are some journals specialized on open source software that have been created exactly for this purpose.

**Comment by ranocha** [comment]
For example, the journal of open source software requires a DOI, e.g. via Zenodo, see https://joss.readthedocs.io/en/latest/submitting.html#the-review-process.

**Comment by ketch** [comment]
I have flipped on Zenodo integration for both RK-Opt and NodePy, so when we do a new release we'll get a DOI.  I didn't see anything about the .json file, so if you know what to do about that please go ahead.

**Comment by ranocha** [comment]
I've submitted a [PR to nodepy](https://github.com/ketch/nodepy/pull/76) and can do the same for RK-Opt. However, I will need the list (and order) of authors for that.
